DROP SCHEMA IF EXISTS public CASCADE;
CREATE SCHEMA IF NOT EXISTS public;

CREATE TABLE post (
	id SERIAL PRIMARY KEY,
	title VARCHAR(1024) NOT NULL UNIQUE
);

CREATE TABLE post_comment (
	id SERIAL PRIMARY KEY,
	review VARCHAR(1024),
	post_id INT NOT NULL,
	CONSTRAINT fk_post 
		FOREIGN KEY(post_id) 
		REFERENCES post(id)
		ON DELETE CASCADE
);

CREATE TABLE post_detail(
	id SERIAL PRIMARY KEY,
	created_by VARCHAR(512) NOT NULL,
	created_on TIMESTAMP WITHOUT TIME ZONE DEFAULT (CURRENT_TIMESTAMP AT TIME ZONE 'utc'),
	post_id BIGINT NOT NULL UNIQUE,
	CONSTRAINT fk_post
		FOREIGN KEY(post_id)
		REFERENCES post(id)
		ON DELETE CASCADE
);

CREATE TABLE tag(
	id SERIAL PRIMARY KEY,
	name VARCHAR(32) NOT NULL UNIQUE
);

CREATE TABLE post_tag(
	id SERIAL PRIMARY KEY,
	post_id BIGINT NOT NULL,
	tag_id BIGINT NOT NULL,
	CONSTRAINT fk_post
		FOREIGN KEY(post_id)
		REFERENCES post(id)
		ON DELETE CASCADE,
	CONSTRAINT fk_tag
		FOREIGN KEY(tag_id)
		REFERENCES tag(id)
		ON DELETE CASCADE
);
